### ISSUE TITLE
Doesn't work with Lenovo IdeaPad Gaming 3

### ISSUE THREAD

**Issue by nestormarius** [laurento/gnome-shell-extension-ideapad#5]
Hello, I've installed the extension on a Lenovo IdeaPad Gaming 3 laptop (GNOME 40/Fedora 34 beta) and nothing happens when I press "Turn Conservation Mode On" in the System menu. I even created the /etc/sudoers.d/ideapad file as instructed.

**Comment by laurento** [comment]
Hi there :)

Make sure the kernel module `ideapad_laptop` is loaded, then have a look at the path `/sys/bus/platform/drivers/ideapad_acpi/`. Can you see any `VCP*` directories?

**Comment by nestormarius** [comment]
Thanks! The `ideapad_laptop` module is loaded by default in Fedora 34. The /sys/bus/platform/drivers/ideapad_acpi/ directory lists a VCP2004:00 directory, which contains the following:
camera_power       driver           fan_mode       fn_lock  modalias  rfkill     touchpad
conservation_mode  driver_override  firmware_node  input    power     subsystem  uevent

**Comment by laurento** [comment]
I just tried on my VM and noticed Fedora is also using `wheel` group instead of `sudo`.

Try with this for your `/etc/sudoers.d/ideapad` file:
`%wheel ALL=(ALL) NOPASSWD: /usr/bin/tee /sys/bus/platform/drivers/ideapad_acpi/VPC????\:??/conservation_mode`

To test the new configuration, try to run from a terminal:
`/bin/sh -c 'echo 0 | sudo tee /sys/bus/platform/drivers/ideapad_acpi/VCP2004:00/conservation_mode'`
you can use 0 or 1 to respectively disable or enable the conservation mode.

Does it work? Do you get any errors?

**Comment by nestormarius** [comment]
Thank you so much for your help. It worked after adding the `%wheel ALL=(ALL) NOPASSWD: /usr/bin/tee /sys/bus/platform/drivers/ideapad_acpi/VPC????\:??/conservation_mode` line.

Keep up the awesome work and thank you for this extension!
