### ISSUE TITLE
Getting incorrect status value

### ISSUE THREAD

**Issue by mumblingdrunkard** [laurento/gnome-shell-extension-ideapad#6]
I've been combing through the extension and have found out that it seems to be one step behind what is actually in the `conservation_mode` file when using the extension on my Lenovo Yoga C940 with Fedora 34 and GNOME 40. This means that the icon is displaying when conservation mode is actually off and the label for the toggle is 'On' when it will turn conservation mode off and vice versa.

I have also noticed that the first time I click the toggle, it will toggle, but neither the indicator nor the toggle label will change. I suspect that this is where the issue lies as on every subsequent toggle it will in fact both toggle and update the indicator and label, effectively putting them one step behind.

I would perhaps hazard a guess at the fetching of the status getting old information, although I do not know how that would come to be. Or that the icon and label are updated before the actual toggle, but that would seem unlikely as the sync should trigger on a change-event?

Sorry to bother you.

Best regards.

mumblingdrunkard

**Comment by mumblingdrunkard** [comment]
I just tried toggling the mode through the command line and it seems that the
extension is in fact receiving old information. It is getting the content of the
file before the file is changed. I still do not know why this happens.

**Comment by laurento** [comment]
First of all, many thanks for reporting your issue :)

It sounds indeed quite awkward to me. Especially your last test. Unfortunately, I can't replicate your issue on my testing environment. I recently switch to openSUSE GNOME:next for testing GNOME 40 support. In fact, Fedora 34 was too buggy for my taste and I was experiencing all sort of issues (e.g. slowness and no extension prefs on wayland).

After all Fedora 34 is still in beta. Perhaps your issue is related with that.

Could you please have a look at the logs `journalctl -f -o cat /usr/bin/gnome-shell` to see if anything relevant pops up while you perform some of those actions?

**Comment by laurento** [comment]
Well, I can keep this issue open. Let me know when Fedora 34 will reach a stable release if you notice any improvements.

Meanwhile, if you fell like experimenting, you could try to run the openSUSE GNOME:next live distro, install the extension and see if you experience the same issue.
